# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f3e3533a5c6fa51acac95e81bdc068ac93fdc2720cf5e1886345d80415ad860f9c09b570fa36c8986613ce7ec28480eff1c9a6432ed46b7260a25ffc5e6d50c

test:
  secret_key_base: dfd77314f8ccd7cd00f75579ffb44738f902fa5c81f74c1e180e0177455ccb7a42c3b89e74846c57169717145c422bbb804eb6bc6d4d62a6998c3c023257d4f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
